# This file was generated by GoReleaser. DO NOT EDIT.
cask "openrelik-cli" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "db908da27b9dcdd947601254301d0d1442086fe0033e7668c742790613595311"
      url "https://github.com/openrelik/openrelik-cli/releases/download/v#{version}/openrelik_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b897a5760b7b277117b7ba08a9a6bbe791e7723dce48393842294360c0344b7"
      url "https://github.com/openrelik/openrelik-cli/releases/download/v#{version}/openrelik_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cf13a2959abd0fe4c8f083f79fb7dafd59744256bba009a401c705db6fcd5bdd"
      url "https://github.com/openrelik/openrelik-cli/releases/download/v#{version}/openrelik_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "53dee4e99fcd0c3365e4b926c90788aac2e67648d520262518d599e1603e9761"
      url "https://github.com/openrelik/openrelik-cli/releases/download/v#{version}/openrelik_linux_arm64.tar.gz"
    end
  end

  name "openrelik-cli"
  desc "A command line tool to interact with the OpenRelik API"
  homepage "https://github.com/openrelik/openrelik-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openrelik"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openrelik"]
  end

  # No zap stanza required

end
