# This file was generated by GoReleaser. DO NOT EDIT.
cask "openrelik" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "a09dc16b33ac28e604eb2a28916317ec3001aaa24fd8704057e54d53d09d1ed6"
      url "https://github.com/openrelik/openrelik-go-client/releases/download/v#{version}/openrelik_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f552654cb9d280ebf9188b6652e72d60016c8d2ecadfd90cd5aa3cf018b5f35"
      url "https://github.com/openrelik/openrelik-go-client/releases/download/v#{version}/openrelik_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a0c9c90d65e58e3e6e70a7b190ae682032b8cde0308eff345b3ed1f9dd285b8"
      url "https://github.com/openrelik/openrelik-go-client/releases/download/v#{version}/openrelik_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "afee425680b17d127fd39feb43d87eebec7ccb40d85bb9ec28a3e7a4febad55a"
      url "https://github.com/openrelik/openrelik-go-client/releases/download/v#{version}/openrelik_linux_arm64.tar.gz"
    end
  end

  name "openrelik"
  desc "A command line tool to interact with the OpenRelik API"
  homepage "https://github.com/openrelik/openrelik-go-client"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openrelik"

  # No zap stanza required

end
