# This file was generated by GoReleaser. DO NOT EDIT.
cask "openrelik" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "42b7766120e1d14ced04ad3d146acdfa91a3b237099920ad82a132cd50a0c387"
      url "https://github.com/openrelik/openrelik-go-client/releases/download/v#{version}/openrelik_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f70eb19d90e1f891787ecefa4182595824774ee6515b2bd0416db2b2202861ea"
      url "https://github.com/openrelik/openrelik-go-client/releases/download/v#{version}/openrelik_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1791f6bd7e66dc88f4707ea24ad088223df3fac3c8f486a57dbf64cebfc47b9e"
      url "https://github.com/openrelik/openrelik-go-client/releases/download/v#{version}/openrelik_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "45f6d7e241cad8ba872be6f47b2e64af8d885da836c7a0d08daaf711fa3d0381"
      url "https://github.com/openrelik/openrelik-go-client/releases/download/v#{version}/openrelik_linux_arm64.tar.gz"
    end
  end

  name "openrelik"
  desc "A command line tool to interact with the OpenRelik API"
  homepage "https://github.com/openrelik/openrelik-go-client"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openrelik"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openrelik"]
  end

  # No zap stanza required

end
