# This file was generated by GoReleaser. DO NOT EDIT.
cask "openrelik" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "3766e8e6a5bdf9abe161278284c75aed3342d5f8d342ebdc31b3bf570c2cc468"
      url "https://github.com/openrelik/openrelik-go-client/releases/download/v#{version}/openrelik_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "35e642c2252ecdf7d6f164448d7e78f0cb8be1b06797bb3355a4ed4e867fd2d8"
      url "https://github.com/openrelik/openrelik-go-client/releases/download/v#{version}/openrelik_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a2e51b0c314f5aa7d828bd9fe5ccf23c7a83e73935c3757be7c371ef87565739"
      url "https://github.com/openrelik/openrelik-go-client/releases/download/v#{version}/openrelik_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "52db48435533c2cb7929e2804a1f62d7a33c05a444e70c13e0c6c747a05f4f01"
      url "https://github.com/openrelik/openrelik-go-client/releases/download/v#{version}/openrelik_linux_arm64.tar.gz"
    end
  end

  name "openrelik"
  desc "A command line tool to interact with the OpenRelik API"
  homepage "https://github.com/openrelik/openrelik-go-client"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openrelik"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openrelik"]
  end

  # No zap stanza required

end
