# This file was generated by GoReleaser. DO NOT EDIT.
cask "openrelik-cli" do
  version "0.3.5"

  on_macos do
    on_intel do
      sha256 "16d490d749437024905ca231e9760361d34745303714a2fcd014059ed09fcc5b"
      url "https://github.com/openrelik/openrelik-cli/releases/download/v#{version}/openrelik_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b7f57f574508d45e880fdaddcbb1cb0918e8fd6bfc339605ed7b6863717b8b5"
      url "https://github.com/openrelik/openrelik-cli/releases/download/v#{version}/openrelik_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6032657808b444dbfa0e024e72de7e764d803c4d8ba51a5f18caf8055b544ca9"
      url "https://github.com/openrelik/openrelik-cli/releases/download/v#{version}/openrelik_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a57689d210dd574a42f745cb1a113921dbaab0a1d05304cb293c98045d01c95e"
      url "https://github.com/openrelik/openrelik-cli/releases/download/v#{version}/openrelik_linux_arm64.tar.gz"
    end
  end

  name "openrelik-cli"
  desc "A command line tool to interact with the OpenRelik API"
  homepage "https://github.com/openrelik/openrelik-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openrelik"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openrelik"]
  end

  # No zap stanza required

end
