# This file was generated by GoReleaser. DO NOT EDIT.
cask "openrelik-cli" do
  version "0.2.7"

  on_macos do
    on_intel do
      sha256 "6c76df0f02cad48388a326be0b3e2708e696bb9eec0c8e46bd4f118be8f44600"
      url "https://github.com/openrelik/openrelik-cli/releases/download/v#{version}/openrelik_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e7ba45d2bdff45433e7cd30e98e60085c9e1ba797c7f9becd7bf8fa6392d8d0"
      url "https://github.com/openrelik/openrelik-cli/releases/download/v#{version}/openrelik_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c65dfe5cf0c636ec4064cf25edf0480d6897ba5af0030c2ffcc45577c2117b12"
      url "https://github.com/openrelik/openrelik-cli/releases/download/v#{version}/openrelik_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5fce719f20c205f256373a1744791ad43a4fea58dd55985567b10e8e8eb5426d"
      url "https://github.com/openrelik/openrelik-cli/releases/download/v#{version}/openrelik_linux_arm64.tar.gz"
    end
  end

  name "openrelik-cli"
  desc "A command line tool to interact with the OpenRelik API"
  homepage "https://github.com/openrelik/openrelik-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openrelik"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openrelik"]
  end

  # No zap stanza required

end
